### ISSUE TITLE
Schedule section and speaker section of website is not responsive

### ISSUE THREAD

**Issue by vjs3** [LNMIIT-FOSS/lnmiit-foss.github.io#24] opened 2016-01-18 21:51 UTC
Most of the sections in this website is working fine in mobile format except that schedule section where circles are not resizing themselves according to the screen size and speaker's section where distorted shape of speaker list can be found.

**Comment by sagaragarwal94** [comment] 2016-01-19 05:15
Yes. The issue is same as https://github.com/LNMIIT-FOSS/lnmiit-foss.github.io/issues/21. It will be solved.
Assigned to @jainmukul

**Comment by vjs3** [comment] 2016-01-19 19:10
@sagaragarwal94 just tested website on various mobile screens and found website is failing to work proprerly in less than 6 inch screen, work should be done in this direction.

**Comment by sagaragarwal94** [comment] 2016-01-19 20:08
Thanks @vjs3 Working on it. @jainmukul have a look on it.
Also if @vjs3 you could help in it, do provide a patch or help to look more issues of it. Thanks.

**Comment by vjs3** [comment] 2016-01-19 20:19
Yes I am doing thing from my side as and when i get time.

**Comment by sagaragarwal94** [comment] 2016-01-22 18:03
Solved.

**Closed by sagaragarwal94** 2016-01-22 18:03 UTC
Labels: bug, enhancement
